dist: trusty
sudo: required

language: c
compiler: gcc

before_install:
  - sudo apt-get update -y
  - sudo apt-get install -y gcc-mingw-w64-x86-64 gcc-mingw-w64-i686
script:
  - mkdir build && cd build && ../configure && make
  - cd ../
  - mkdir build-win64 && cd build-win64 && ../configure CC='x86_64-w64-mingw32-gcc -m64 -static-libgcc' --enable-all-static --enable-shared --host=x86_64-w64-mingw32 --prefix=`pwd`/install && make && make install
  - cd ../
  - mkdir build-win32 && cd build-win32 && ../configure CC='i686-w64-mingw32-gcc -m32 -static-libgcc' --enable-all-static --enable-shared --host=i686-w64-mingw32 --prefix=`pwd`/install && make && make install
  - cd ../
before_deploy:
  - export GIT_TAG=`git describe --abbrev=0 --tags`
  - mkdir packages
  - cd build-win64/install/ && zip -q ../../packages/yp-spur.win64.$GIT_TAG.zip -r $(ls)
  - cd ../../
  - cd build-win32/install/ && zip -q ../../packages/yp-spur.win32.$GIT_TAG.zip -r $(ls)
  - cd ../../

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "L0+bhmrOKNGDP4q25T3+T3AKyRgl+ecVIkFVzkhA8piEljBNkogtRhgnRUHMl+VF65l5erOT4re34uODtbBoEIaTqD89bgf8I7pyG8iKDCoUO/FEyBoXPiysz3LqOnFfXCULwRiMZg3gff1vcEtKlP/42uqe+OK5QIke0vgS1qrZCtPn6BETe6YoHryWfF0wueOfQVUDrKFl5nFxnADvQK3/6ygffbFJscL1rrlgq8/RBUyyK+jsBXIs/NFho4HJUCyxogCJDtZU78k8/gExl9PBJS2wVTdyuugM+L934oUJE8tVzYWkBQmnXEuHL5ASzbqGDje59y7C/G9ARmx6sq18613K0DrjhB8Tb++DBWqoEeSblkYoFQIsRa8w0ugYXxPBEJ9l0E0KSppLfqvUhKwEGVGL3EPzSAY1fvxa8VGaW5k8Rm9HRpavo5Q0xZN0KFHkEDZWHoIQLgTFN+gzthg1w+oLxvbKYWh1wwL1iZw0L30fx5ZM/+J8cIEYNMvYlYL7TVG76Tqzh8Ij2vZcjyxBJMSafwasgZrAD0Mgy+1L2fQlDwBV/uUc2eX9nQFsa8MqlhyvM8yo6LryM7WpsBpZsNqXH89rpiOCzR2pdWJtInee98n2Nw1nM25mtmEjK0N0c1uxe2O0eMXjKjH603ps/84N5Rf8cKqmbAWKwHM="
  file:
    - packages/yp-spur.win64.$GIT_TAG.zip
    - packages/yp-spur.win32.$GIT_TAG.zip
  on:
    tags: true

