ARG UBUNTU_VERSION=bionic
FROM ubuntu:${UBUNTU_VERSION}

RUN apt-get -qq update \
  && apt-get install -y --no-install-recommends build-essential cmake libgtest-dev
# don't clean apt-cache to reuse later

ENV CTEST_OUTPUT_ON_FAILURE=1

RUN mkdir -p /tmp/gtest \
  && cd /tmp/gtest \
  && cmake /usr/src/gtest \
  && make -j \
  && cp *.a /usr/lib/ \
  && rm -rf /tmp/gtest

ENV CTEST_OUTPUT_ON_FAILURE=1

COPY ./ /yp-spur
RUN mkdir -p /yp-spur/build
WORKDIR /yp-spur/build
RUN cmake .. && make -j && make test && make install
