name: ci-alpine-ros
on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read
  packages: read

jobs:
  test:
    uses: alpine-ros/alpine-ros-ci-workflows/.github/workflows/ros1.yaml@main
    with:
      abuild-env: CTEST_OUTPUT_ON_FAILURE=1
